services:

  db:
    image: postgres:14.4
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sample

  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - 6030:6379
      - 6031:8001
    environment:
      - REDIS_ARGS="--requirepass redispassword123"
