services:

  db:
    image: postgres:14.4
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sample
    volumes:
      - db_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080

  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - 6030:6379
    environment:
      - REDIS_PASSWORD=redispassword123
    volumes:
      - redis_data:/data
    command:
      - /bin/sh
      - -c
      - "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD?:REDIS_PASSWORD is no set}"

volumes:
  db_data:
  redis_data:
