services:

  db:
    image: postgres:15.2-alpine3.17
    restart: always
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - db_data2:/var/lib/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 6001:8080

  redis:
    image: redis:7.0.4
    restart: always
    ports:
      - 6030:6379
    environment:
      - REDIS_PASSWORD=redispassword123
    volumes:
      - redis_data:/data
    command:
      - /bin/sh
      - -c
      - "redis-server --appendonly yes --requirepass $${REDIS_PASSWORD?:REDIS_PASSWORD is no set}"

volumes:
  db_data2:
  redis_data:
