
export default function LoremIpsum() {
    return <p>{LOREM}</p>;
}

const LOREM = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultrices, massa id sollicitudin rutrum, neque tortor maximus libero, sed ultrices enim massa ac enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris efficitur diam risus, eget facilisis diam cursus non. Proin vulputate mi at sapien malesuada, ac hendrerit mauris dignissim. Morbi at urna nulla. Aenean id sollicitudin eros. Nunc mi dolor, ultrices eget ultrices sed, consectetur sit amet felis. Quisque a finibus est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris eu ex condimentum, vestibulum lorem eu, congue dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus a arcu vel ipsum bibendum eleifend. Donec cursus mi sit amet vestibulum lobortis. Duis ipsum orci, congue at nulla id, varius aliquam sem. Pellentesque gravida tincidunt odio sed rutrum. Nulla facilisis tempor quam ac ullamcorper.

Aliquam pellentesque est dolor, hendrerit tempor dui sodales ut. Maecenas eu erat ac urna commodo consequat. Vestibulum laoreet facilisis odio in rutrum. Sed ex orci, ornare a rutrum vel, rutrum in mauris. Nullam interdum, arcu et porttitor tincidunt, orci sapien tristique tellus, eu ornare augue leo at orci. Fusce sagittis massa eu enim mollis finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ut sagittis arcu. Duis a mollis eros, eu porttitor ante.

Pellentesque non leo at mi ullamcorper luctus sed non diam. Nam non sollicitudin justo. Aliquam eget commodo magna. Phasellus sagittis ante ex, nec placerat dolor rhoncus nec. Morbi quis laoreet lectus. Nullam sit amet turpis nec mi rhoncus fermentum quis ut sapien. In in turpis lacus. Fusce vitae dapibus lectus. Vestibulum semper, nulla sed mollis mollis, nibh magna imperdiet quam, at porta odio sem eget ipsum. Maecenas et tortor sit amet nisi hendrerit porta non id arcu. Sed sit amet est ac velit luctus eleifend. Curabitur interdum maximus nisi.

Aliquam fringilla aliquam tempus. Nam vulputate tellus at augue vulputate, et suscipit tellus pretium. Suspendisse accumsan ligula vitae diam posuere, eget cursus arcu commodo. Ut faucibus elementum quam eget lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam tempor sit amet purus ac commodo. Aliquam gravida enim diam, a blandit ex venenatis quis.

Duis iaculis interdum dolor, blandit tristique turpis lobortis id. Aenean venenatis faucibus massa, sed gravida tortor malesuada quis. Vestibulum eu odio orci. Pellentesque id sem ac felis feugiat mollis. Duis sed arcu luctus, ornare neque quis, eleifend justo. Ut sem orci, imperdiet ac dictum vel, congue ut urna. Proin in tellus risus. Nunc suscipit urna enim, vitae interdum elit sollicitudin in. Pellentesque tincidunt, eros at placerat faucibus, erat velit pharetra turpis, pellentesque euismod magna purus sed magna. Nullam lacinia facilisis elit, nec vulputate ligula finibus ut. Etiam vitae magna nec arcu tempor vehicula et in ligula.`;