name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Vercel
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: yarn install --frozen-lockfile
    
    # Deploy
    - uses: amondnet/vercel-action@v20 #deploy
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
